"use client";
import { useEffect,useMemo,useState } from "react";
import { PRODUCTS } from "@/lib/products";
import { supabase } from "@/lib/supabase";
import { buildFefoUsePlan, expiryState, sortBatchesFefo, type ExpiryBatch } from "@/lib/expiry";

type Batch=ExpiryBatch&{quantity_received:number;notes:string|null;created_at:string};
function isoToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function isoDateAfter(days:number){const d=new Date();d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function daysLeft(date:string){const a=new Date(`${isoToday()}T12:00:00`);const b=new Date(`${date}T12:00:00`);return Math.round((b.getTime()-a.getTime())/86400000)}

export default function ExpiryBoard(){
 const [rows,setRows]=useState<Batch[]>([]),[product,setProduct]=useState(PRODUCTS[0].id),[qty,setQty]=useState(0),[expiry,setExpiry]=useState(isoDateAfter(6)),[note,setNote]=useState(""),[error,setError]=useState(""),[useQty,setUseQty]=useState<Record<string,number>>({}),[saving,setSaving]=useState(false);
 async function load(){const {data,error}=await supabase.from("hajj_batches").select("id,product_code,quantity_received,quantity_remaining,received_date,expiry_date,notes,created_at").gt("quantity_remaining",0).order("expiry_date").order("received_date").order("created_at");if(error)setError(error.message);else setRows(sortBatchesFefo((data||[]) as Batch[]))}
 useEffect(()=>{load()},[]);
 async function save(){if(qty<=0||!expiry){setError("Enter quantity and expiry date.");return}const {error}=await supabase.from("hajj_batches").insert({product_code:product,quantity_received:qty,quantity_remaining:qty,received_date:isoToday(),expiry_date:expiry,notes:note||null});if(error)setError(error.message);else{setQty(0);setExpiry(isoDateAfter(6));setNote("");setError("");await load()}}
 async function useStock(productCode:string){const requested=Math.floor(useQty[productCode]||0);const available=rows.filter(r=>r.product_code===productCode).reduce((sum,r)=>sum+r.quantity_remaining,0);if(requested<=0){setError("Enter the quantity used or sold.");return}if(requested>available){setError(`Only ${available} available for this item.`);return}setSaving(true);setError("");const productRows=rows.filter(r=>r.product_code===productCode);for(const step of buildFefoUsePlan(productRows,requested)){const row=productRows.find(r=>r.id===step.id)!;const {error}=await supabase.from("hajj_batches").update({quantity_remaining:row.quantity_remaining-step.quantity,updated_at:new Date().toISOString()}).eq("id",step.id).eq("quantity_remaining",row.quantity_remaining);if(error){setError(`Could not use stock: ${error.message}`);setSaving(false);await load();return}}setUseQty(q=>({...q,[productCode]:0}));setSaving(false);await load()}
 const total=useMemo(()=>rows.reduce((s,r)=>s+r.quantity_remaining,0),[rows]);
 const groups=useMemo(()=>PRODUCTS.map(product=>({product,rows:rows.filter(row=>row.product_code===product.id)})).filter(group=>group.rows.length),[rows]);
 return <section className="card"><div className="section-head"><div><h2>Available stock & expiry</h2><p className="muted">Use the earliest expiry first. If dates match, use the oldest received batch first (FIFO).</p></div><div className="notice good">Batch stock: <strong>{total}</strong></div></div>
  <div className="grid3"><label className="stack">Product<select value={product} onChange={e=>setProduct(e.target.value)}>{PRODUCTS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="stack">Received quantity<input type="number" min="1" value={qty||""} onChange={e=>setQty(Number(e.target.value))}/></label><label className="stack">Expiry date (6-day shelf life)<input type="date" min={isoToday()} value={expiry} onChange={e=>setExpiry(e.target.value)}/></label></div>
  <label className="stack" style={{marginTop:10}}>Notes<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional batch or delivery note"/></label><div className="actions"><button className="btn primary" onClick={save}>Add expiry batch</button></div>{error&&<div className="notice warn">{error}</div>}
  <div className="expiry-list">{groups.map(({product,rows:productRows})=><div className="fifo-group" key={product.id}><div className="fifo-head"><div><h3>{product.name}</h3><small>{productRows.reduce((sum,row)=>sum+row.quantity_remaining,0)} available · {productRows.length} batch{productRows.length===1?"":"es"}</small></div><div className="fifo-use"><input aria-label={`Quantity used for ${product.name}`} type="number" min="1" placeholder="Used" value={useQty[product.id]||""} onChange={e=>setUseQty(q=>({...q,[product.id]:Number(e.target.value)}))}/><button className="btn" disabled={saving} onClick={()=>useStock(product.id)}>Use stock</button></div></div>{productRows.map((r,index)=>{const status=expiryState(daysLeft(r.expiry_date));return <div className={`expiry-row ${status.className}`} key={r.id}><div><div className="batch-title">{index===0&&<span className="fifo-badge">USE FIRST</span>}<strong>{r.quantity_remaining} available</strong></div><small>Received {r.received_date} · Expires {r.expiry_date}</small><small>{status.label}{r.notes?` · ${r.notes}`:""}</small></div><div className="batch-count"><span>Batch</span><strong>{r.quantity_remaining}/{r.quantity_received}</strong></div></div>})}</div>)}{!rows.length&&<div className="notice">No expiry batches yet. Add today&apos;s available stock above.</div>}</div>
 </section>
}
